In [2]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdcanon import canon_smarts
from pandarallel import pandarallel
pandarallel.initialize(nb_workers=8,progress_bar=True)

INFO: Pandarallel will run on 8 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

In [ ]:
df1 = pd.read_csv(r'result/represent_fg1_fg2_1044.csv') #1044 没有考虑去重前 重复
df_1044 = pd.read_csv(r'data/avail_smiles_1044.csv')

In [4]:

df1.drop_duplicates('canon_smarts') #1044含有多少键?

,fg1,fg2,fg1_fg2,fg1_fg2_marked,bond,atom1,atom2,canon_smarts,avail,type,avail0,mol_source,is_1044
0,[C]1-[c]2[c][c][c][c][c]2-[c]2[c][c][c][c][c]2-1,[#6]1([#6]2)[#6][#6][#6][#6]2[#6][#6][#6]1,C1(-c2ccccc2-c2ccccc2-1)-[#6]1[#6][#6]2[#6][#6...,[C:1]1(-c2ccccc2-c2ccccc2-1)-[#6:2]1[#6][#6]2[...,SINGLE,C,C,[#6]1([#6]([#6][#6]2([#6][#6]1[#6][#6][#6]2))-...,['C1(C2(C(C3)CC4CC3CC2C4)C5=C6C=CC=C5)=C6C=CC=...,fg1_fg2,c1ccc2c(c1)-c1ccccc1C21C2CC3CC(C2)CC1C3,3w2,True
1,[#8][#6;H2][#8],[#16],[#8]([#6&H2][#8])-[#16],[#8:1]([#6&H2][#8])-[#16:2],SINGLE,O,S,[#6;H2]([#8]-[#16])[#8],['O=S1(=O)CS(=O)(=O)OCO1'],fg1_fg2,O=S1(=O)CS(=O)(=O)OCO1,463,True
2,[#7;X3H0]([#6])([#6])([#6]),[#7],[#7&X3&H0]([#6]#[#7])([#6])[#6],[#7&X3&H0]([#6:1]#[#7:2])([#6])[#6],TRIPLE,C,N,[#6](#[#7])[#7;X3;H0]([#6])[#6],['N#CN1CCOCC1'],fg1_fg2,N#CN1CCOCC1,463,True
3,"[#7;X3H1+0,X3H2+0,X3H0+0][#7;X3H1+0,X3H2+0,X3H...",[#6],"[#7;X3&H1&+0,X3&H2&+0,X3&H0&+0]([#7;X3&H1&+0,X...","[#7;X3&H1&+0,X3&H2&+0,X3&H0&+0:1]([#7;X3&H1&+0...",SINGLE,N,C,"[#6]-[#7;X3&H0&+0,X3&H1&+0,X3&H2&+0][#7;X3&H0&...","['N#CCCNN', 'Cn1[nH]ccc1=O', 'CN1CCN(N)CC1']",fg1_fg2,N#CCCNN,463,True
4,[#7;X3H0]([#6])([#6])([#6]),[#6],[#7&X3&H0]([#6]=[#6])([#6])[#6],[#7&X3&H0]([#6:1]=[#6:2])([#6])[#6],DOUBLE,C,C,[#6](=[#6])[#7;X3;H0]([#6])[#6],"['CC(=O)/C=C/N(C)C', 'C=C1N(C)c2ccccc2C1(C)C',...",fg1_fg2,CC(=O)/C=C/N(C)C,463,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5742,[#16]1[#6][#16][#6]=[#6]1,[#6],[#16]1[#6]([#16][#6]=[#6]1)=[#6],[#16]1[#6:1]([#16][#6]=[#6]1)=[#6:2],DOUBLE,C,C,[#6]1(=[#6])([#16][#6]=[#6][#16]1),['C1=CSC(=C2SC=CS2)S1'],fg1_fg2,C1=CSC(=C2SC=CS2)S1,581,True
5743,[#16]1[#6][#16][#6]=[#6]1,[#6][#16v2][#6],[#16]1[#6]([#16][#6]=[#6]1)=[#6][#16&v2][#6],[#16]1[#6:1]([#16][#6]=[#6]1)=[#6:2][#16&v2][#6],DOUBLE,C,C,[#6](=[#6]1([#16][#6]=[#6][#16]1))[#16;v2][#6],['C1=CSC(=C2SC=CS2)S1'],fg1_fg2,C1=CSC(=C2SC=CS2)S1,581,True
5744,[#16]1[#6][#16][#6]=[#6]1,[#16]1[#6][#16][#6]=[#6]1,[#16]1[#6]([#16][#6]=[#6]1)=[#6]1[#16][#6]=[#6...,[#16]1[#6:1]([#16][#6]=[#6]1)=[#6:2]1[#16][#6]...,DOUBLE,C,C,[#6]2(=[#6][#16][#6](=[#6]1([#16][#6]=[#6][#16...,['C1=CSC(=C2SC=CS2)S1'],fg1_fg2,C1=CSC(=C2SC=CS2)S1,581,True
5745,[#6]1[#8][#6][#7][#6]1,[CX4;!R][CX4;!R][CX4;!R],[#6]1[#8][#6][#7][#6]1-[C&X4&!R]([C&X4&!R])[C&...,[#6]1[#8][#6][#7][#6:1]1-[C&X4&!R:2]([C&X4&!R]...,SINGLE,C,C,[#6]1([#6]([#7][#6][#8]1)-[C;X4;!R]([C;X4;!R])...,['CC(C)[C@@H]1COC(=S)N1'],fg1_fg2,CC(C)[C@@H]1COC(=S)N1,581,True
5746,[#6]1[#8][#6][#7][#6]1,[#8],[#6]1([#8][#6][#7][#6]1)=[#8],[#6:1]1([#8][#6][#7][#6]1)=[#8:2],DOUBLE,C,O,[#6]1([#6][#7][#6][#8]1)=[#8],['CN1CC(=O)OC1=O'],fg1_fg2,CN1CC(=O)OC1=O,581,True

In [5]:
H_inner_marked_contain_dup = pd.read_csv('data/H_inner_marked_contain_dup.csv',delimiter='\t')
inner_marked_contain_dup = pd.read_csv('data/inner_marked_contain_dup.csv',delimiter='\t')

for index, row in df1.iterrows():
    s = H_inner_marked_contain_dup.loc[H_inner_marked_contain_dup['smarts_inner_marked'] == row['fg1_fg2_marked'],'smarts_marked_oxygen']
    if s.empty:
        continue
    
    v = H_inner_marked_contain_dup.loc[H_inner_marked_contain_dup['smarts_marked_oxygen']==s.values[0], 'smarts_inner_marked'] .values
    for val in v:
        new_row = row.copy()
        new_row['fg1_fg2_marked'] = val
        df1.loc[df1.__len__()] = new_row


for index, row in df1.iterrows():
    s = inner_marked_contain_dup.loc[inner_marked_contain_dup['smarts_marked'] == row['fg1_fg2_marked'],'smarts_marked_oxygen']
    if s.empty:
        continue
    
    v = inner_marked_contain_dup.loc[inner_marked_contain_dup['smarts_marked_oxygen']==s.values[0], 'smarts_marked'] .values
    for val in v:
        new_row = row.copy()
        new_row['fg1_fg2_marked'] = val
        df1.loc[df1.__len__()] = new_row

In [6]:
df1.drop_duplicates('canon_smarts')

,fg1,fg2,fg1_fg2,fg1_fg2_marked,bond,atom1,atom2,canon_smarts,avail,type,avail0,mol_source,is_1044
0,[C]1-[c]2[c][c][c][c][c]2-[c]2[c][c][c][c][c]2-1,[#6]1([#6]2)[#6][#6][#6][#6]2[#6][#6][#6]1,C1(-c2ccccc2-c2ccccc2-1)-[#6]1[#6][#6]2[#6][#6...,[C:1]1(-c2ccccc2-c2ccccc2-1)-[#6:2]1[#6][#6]2[...,SINGLE,C,C,[#6]1([#6]([#6][#6]2([#6][#6]1[#6][#6][#6]2))-...,['C1(C2(C(C3)CC4CC3CC2C4)C5=C6C=CC=C5)=C6C=CC=...,fg1_fg2,c1ccc2c(c1)-c1ccccc1C21C2CC3CC(C2)CC1C3,3w2,True
1,[#8][#6;H2][#8],[#16],[#8]([#6&H2][#8])-[#16],[#8:1]([#6&H2][#8])-[#16:2],SINGLE,O,S,[#6;H2]([#8]-[#16])[#8],['O=S1(=O)CS(=O)(=O)OCO1'],fg1_fg2,O=S1(=O)CS(=O)(=O)OCO1,463,True
2,[#7;X3H0]([#6])([#6])([#6]),[#7],[#7&X3&H0]([#6]#[#7])([#6])[#6],[#7&X3&H0]([#6:1]#[#7:2])([#6])[#6],TRIPLE,C,N,[#6](#[#7])[#7;X3;H0]([#6])[#6],['N#CN1CCOCC1'],fg1_fg2,N#CN1CCOCC1,463,True
3,"[#7;X3H1+0,X3H2+0,X3H0+0][#7;X3H1+0,X3H2+0,X3H...",[#6],"[#7;X3&H1&+0,X3&H2&+0,X3&H0&+0]([#7;X3&H1&+0,X...","[#7;X3&H1&+0,X3&H2&+0,X3&H0&+0:1]([#7;X3&H1&+0...",SINGLE,N,C,"[#6]-[#7;X3&H0&+0,X3&H1&+0,X3&H2&+0][#7;X3&H0&...","['N#CCCNN', 'Cn1[nH]ccc1=O', 'CN1CCN(N)CC1']",fg1_fg2,N#CCCNN,463,True
4,[#7;X3H0]([#6])([#6])([#6]),[#6],[#7&X3&H0]([#6]=[#6])([#6])[#6],[#7&X3&H0]([#6:1]=[#6:2])([#6])[#6],DOUBLE,C,C,[#6](=[#6])[#7;X3;H0]([#6])[#6],"['CC(=O)/C=C/N(C)C', 'C=C1N(C)c2ccccc2C1(C)C',...",fg1_fg2,CC(=O)/C=C/N(C)C,463,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5742,[#16]1[#6][#16][#6]=[#6]1,[#6],[#16]1[#6]([#16][#6]=[#6]1)=[#6],[#16]1[#6:1]([#16][#6]=[#6]1)=[#6:2],DOUBLE,C,C,[#6]1(=[#6])([#16][#6]=[#6][#16]1),['C1=CSC(=C2SC=CS2)S1'],fg1_fg2,C1=CSC(=C2SC=CS2)S1,581,True
5743,[#16]1[#6][#16][#6]=[#6]1,[#6][#16v2][#6],[#16]1[#6]([#16][#6]=[#6]1)=[#6][#16&v2][#6],[#16]1[#6:1]([#16][#6]=[#6]1)=[#6:2][#16&v2][#6],DOUBLE,C,C,[#6](=[#6]1([#16][#6]=[#6][#16]1))[#16;v2][#6],['C1=CSC(=C2SC=CS2)S1'],fg1_fg2,C1=CSC(=C2SC=CS2)S1,581,True
5744,[#16]1[#6][#16][#6]=[#6]1,[#16]1[#6][#16][#6]=[#6]1,[#16]1[#6]([#16][#6]=[#6]1)=[#6]1[#16][#6]=[#6...,[#16]1[#6:1]([#16][#6]=[#6]1)=[#6:2]1[#16][#6]...,DOUBLE,C,C,[#6]2(=[#6][#16][#6](=[#6]1([#16][#6]=[#6][#16...,['C1=CSC(=C2SC=CS2)S1'],fg1_fg2,C1=CSC(=C2SC=CS2)S1,581,True
5745,[#6]1[#8][#6][#7][#6]1,[CX4;!R][CX4;!R][CX4;!R],[#6]1[#8][#6][#7][#6]1-[C&X4&!R]([C&X4&!R])[C&...,[#6]1[#8][#6][#7][#6:1]1-[C&X4&!R:2]([C&X4&!R]...,SINGLE,C,C,[#6]1([#6]([#7][#6][#8]1)-[C;X4;!R]([C;X4;!R])...,['CC(C)[C@@H]1COC(=S)N1'],fg1_fg2,CC(C)[C@@H]1COC(=S)N1,581,True
5746,[#6]1[#8][#6][#7][#6]1,[#8],[#6]1([#8][#6][#7][#6]1)=[#8],[#6:1]1([#8][#6][#7][#6]1)=[#8:2],DOUBLE,C,O,[#6]1([#6][#7][#6][#8]1)=[#8],['CN1CC(=O)OC1=O'],fg1_fg2,CN1CC(=O)OC1=O,581,True

In [ ]:
fg1_fg2 = pd.read_csv('data/type4_construct_fg_fg.csv',delimiter='\t',
                      usecols=['fg1_fg2','fg1_fg2_marked','canon_smarts'])
inner_marked_comb = pd.concat([fg1_fg2,
                               H_inner_marked_contain_dup.rename(columns={'smarts':'fg1_fg2','smarts_inner_marked':'fg1_fg2_marked','smarts_marked_oxygen':'canon_smarts'}), 
                               inner_marked_contain_dup.rename(columns={'smarts':'fg1_fg2','smarts_marked':'fg1_fg2_marked','smarts_marked_oxygen':'canon_smarts'})])
inner_marked_comb.head(2)

,fg1_fg2,fg1_fg2_marked,canon_smarts
0,[#6]12[#6]3([#6][#6][#6]3)[#6]=[#7][#6]1[#6]([...,[#6]12[#6]3([#6][#6][#6]3)[#6]=[#7][#6]1[#6:1]...,[#6]1([#6]([#6]3([#6]([#6][#6]1)[#6]2([#6][#6]...
1,[#6]12[#6]3([#6][#6]([#6]3)-c3c4c5c(oc4ccc3)cc...,[#6]12[#6]3([#6][#6:1]([#6]3)-[c:2]3c4c5c(oc4c...,[#6]1([#6]([#6][#6]31([#6]2([#6]([#6][#6][#6][...

In [8]:
inner_marked_comb

,fg1_fg2,fg1_fg2_marked,canon_smarts
0,[#6]12[#6]3([#6][#6][#6]3)[#6]=[#7][#6]1[#6]([...,[#6]12[#6]3([#6][#6][#6]3)[#6]=[#7][#6]1[#6:1]...,[#6]1([#6]([#6]3([#6]([#6][#6]1)[#6]2([#6][#6]...
1,[#6]12[#6]3([#6][#6]([#6]3)-c3c4c5c(oc4ccc3)cc...,[#6]12[#6]3([#6][#6:1]([#6]3)-[c:2]3c4c5c(oc4c...,[#6]1([#6]([#6][#6]31([#6]2([#6]([#6][#6][#6][...
2,[#6]12[#6]3([#6][#6][#6]3)[#6]=[#7][#6]1[#6][#...,[#6]12[#6]3([#6][#6][#6]3)[#6]=[#7][#6]1[#6][#...,[#6]1([#6]([#6][#6]3([#6]([#6]1)[#6]2([#6][#6]...
3,[#6]12[#6]3([#6][#6]([#6]3)-c3cc4c5c(oc4cc3)cc...,[#6]12[#6]3([#6][#6:1]([#6]3)-[c:2]3cc4c5c(oc4...,[#6]1([#6]([#6][#6]31([#6]2([#6]([#6][#6][#6][...
4,[#6]12[#6]3([#6][#6][#6]3)[#6]=[#7][#6]1([#6][...,[#6]12[#6]3([#6][#6][#6]3)[#6]=[#7][#6:1]1([#6...,[#6]1([#6]3([#6]([#6][#6][#6]1)[#6]2([#6][#6][...
...,...,...,...
5898,[#33],NaN,NaN
5899,[#34],NaN,NaN
5900,[#35],NaN,NaN
5901,[#52],NaN,NaN
5902,[#53],NaN,NaN

In [11]:
from utils.get_marked import get_Hatom1, get_inner_ba12, convert_implicit_H

def deal_H(s:str):
    if ':1' in s:
        mol = Chem.MolFromSmarts(s)
    else:
        s0 = convert_implicit_H(s) #氢
        if s0 == '[N]1(=[C][N;!H0][C][C]1)':
            print(s)
        mol = Chem.MolFromSmarts(s0) 
    return mol

# 1044个化合物有多少个键? 6k 5283

df1['s'] = df1['fg1_fg2_marked'].parallel_apply(deal_H)

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=1184), Label(value='0 / 1184'))), …

[N:2]1C=NCC1
[N:2]1C=NCC1

In [10]:
df1[~df1['fg1_fg2_marked'].str.contains(':1')]

,fg1,fg2,fg1_fg2,fg1_fg2_marked,bond,atom1,atom2,canon_smarts,avail,type,avail0,mol_source,is_1044
1624,[c]1([s][c][n]2)[c]2[c][c][c][c]1,H,[c]1([s][c][n]2)[c]2[c][c][c][c]1,c12scnc1c[c:2]cc2,SINGLE,C,H,[s]1([c][n][c]2([c][c](#[#8])[c][c][c]12)),"['c1ccc2scnc2c1', 'Sc1nc2ccccc2s1']",Hinner,c1ccc2scnc2c1,463,True
1625,[c]1([s][c][n]2)[c]2[c][c][c][c]1,H,[c]1([s][c][n]2)[c]2[c][c][c][c]1,c12s[c:2]nc1cccc2,SINGLE,C,H,[s]1([c]([n][c]2([c]1[c][c][c][c]2))#[#8]),"['c1ccc2scnc2c1', 'Nc1ccc2scnc2c1']",Hinner,c1ccc2scnc2c1,463,True
1626,[c]1([o][c][n]2)[c]2[c][c][c][c]1,H,[c]1([o][c][n]2)[c]2[c][c][c][c]1,c12ocnc1ccc[c:2]2,SINGLE,C,H,[o]1([c][n][c]2([c]1[c](#[#8])[c][c][c]2)),"['c1ccc2ocnc2c1', 'Cc1ccc2ocnc2c1', 'CSc1nc2cc...",Hinner,c1ccc2ocnc2c1,463,True
1627,[c]1([o][c][n]2)[c]2[c][c][c][c]1,H,[c]1([o][c][n]2)[c]2[c][c][c][c]1,c12ocnc1cc[c:2]c2,SINGLE,C,H,[o]1([c][n][c]2([c]1[c][c](#[#8])[c][c]2)),"['c1ccc2ocnc2c1', 'Cc1ccc2ocnc2c1', 'CSc1nc2cc...",Hinner,c1ccc2ocnc2c1,463,True
1628,[c]1([o][c][n]2)[c]2[c][c][c][c]1,H,[c]1([o][c][n]2)[c]2[c][c][c][c]1,c12ocnc1c[c:2]cc2,SINGLE,C,H,[o]1([c][n][c]2([c][c](#[#8])[c][c][c]12)),"['c1ccc2ocnc2c1', 'CSc1nc2ccccc2o1', 'c1ccc(-c...",Hinner,c1ccc2ocnc2c1,463,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7145,[c]1([c][c][n][c]2)[c]2[c][n][c][n]1,H,[c]1([c][c][n][c]2)[c]2[c][n][c][n]1,c12[c:2]cncc1cncn2,SINGLE,C,H,[n]2([c][n][c]1([c](#[#8])[c][n][c][c]1[c]2)),['O=c1[nH]cnc2ccncc12'],Hinner,O=c1[nH]cnc2ccncc12,581,True
7146,[c]1([c][c][n][c]2)[c]2[n][c][c][n]1,H,[c]1([c][c][n][c]2)[c]2[n][c][c][n]1,c12ccncc1n[c:2]cn2,SINGLE,C,H,[n]1([c](#[#8])[c][n][c]2([c]1[c][n][c][c]2)),"['Clc1cc2nccnc2cn1', 'Clc1nccc2nccnc12']",Hinner,Clc1cc2nccnc2cn1,581,True
7147,[c]1([c][c][n][c]2)[c]2[c][n][c][n]1,H,[c]1([c][c][n][c]2)[c]2[c][n][c][n]1,c12ccncc1cn[c:2]n2,SINGLE,C,H,[n]2([c]([n][c]1([c]([c][n][c][c]1)[c]2))#[#8]),['O=c1[nH]cnc2ccncc12'],Hinner,O=c1[nH]cnc2ccncc12,581,True
7148,[c]1([c][c][n][c]2)[c]2[c][n][c][n]1,H,[c]1([c][c][n][c]2)[c]2[c][n][c][n]1,c12c[c:2]ncc1cncn2,SINGLE,C,H,[n]2([c][n][c]1([c]([c][n][c](#[#8])[c]1)[c]2)),['O=c1[nH]cnc2ccncc12'],Hinner,O=c1[nH]cnc2ccncc12,581,True
7149,[c]1([c][c][c][n]2)[c]2[c][n][c][n]1,H,[c]1([c][c][c][n]2)[c]2[c][n][c][n]1,c12cccnc1c[n:2]cn2,SINGLE,N,H,[n]2(#[#8])([c][n][c]1([c]([n][c][c][c]1)[c]2)),['O=c1[nH]cnc2cccnc12'],Hinner,O=c1[nH]cnc2cccnc12,581,True

In [213]:
# df1[df1['fg1_fg2_marked']=='[N:2]1C=NCC1']
df1[df1['fg1_fg2_marked']=='[#6:1]1[#6:2][#6][#6]1']

,fg1,fg2,fg1_fg2,fg1_fg2_marked,bond,atom1,atom2,canon_smarts,avail,type,avail0,mol_source,is_1044,s
2226,[#6]1[#6][#6][#6]1,[#6]1[#6][#6][#6]1,[#6]1[#6][#6][#6]1,[#6:1]1[#6:2][#6][#6]1,SINGLE,C,C,[#6]1([#6]([#6]([#6]1)#[#8])#[#8]),"['O=C1CCC1', 'O=CC1CCC1', 'CC(=O)C1CCC1', 'c1c...",inner,O=C1CCC1,463,True,<rdkit.Chem.rdchem.Mol object at 0x770c68c32270>
8419,[#6]1[#6][#6][#6]1,[#6]1[#6][#6][#6]1,[#6]1[#6][#6][#6]1,[#6:1]1[#6:2][#6][#6]1,SINGLE,C,C,[#6]1([#6]([#6]([#6]1)#[#8])#[#8]),"['O=C1CCC1', 'O=CC1CCC1', 'CC(=O)C1CCC1', 'c1c...",inner,O=C1CCC1,463,True,<rdkit.Chem.rdchem.Mol object at 0x7710aae8f770>

In [13]:
df1[~df1['fg1_fg2_marked'].isin(inner_marked_comb['fg1_fg2_marked'])]

Empty DataFrame
Columns: [fg1, fg2, fg1_fg2, fg1_fg2_marked, bond, atom1, atom2, canon_smarts, avail, type, avail0, mol_source, is_1044, s]
Index: []

In [14]:
df1['canon_smarts'].unique().__len__()

5747

In [15]:
df1.drop_duplicates('canon_smarts')

,fg1,fg2,fg1_fg2,fg1_fg2_marked,bond,atom1,atom2,canon_smarts,avail,type,avail0,mol_source,is_1044,s
0,[C]1-[c]2[c][c][c][c][c]2-[c]2[c][c][c][c][c]2-1,[#6]1([#6]2)[#6][#6][#6][#6]2[#6][#6][#6]1,C1(-c2ccccc2-c2ccccc2-1)-[#6]1[#6][#6]2[#6][#6...,[C:1]1(-c2ccccc2-c2ccccc2-1)-[#6:2]1[#6][#6]2[...,SINGLE,C,C,[#6]1([#6]([#6][#6]2([#6][#6]1[#6][#6][#6]2))-...,['C1(C2(C(C3)CC4CC3CC2C4)C5=C6C=CC=C5)=C6C=CC=...,fg1_fg2,c1ccc2c(c1)-c1ccccc1C21C2CC3CC(C2)CC1C3,3w2,True,<rdkit.Chem.rdchem.Mol object at 0x7c09775b1310>
1,[#8][#6;H2][#8],[#16],[#8]([#6&H2][#8])-[#16],[#8:1]([#6&H2][#8])-[#16:2],SINGLE,O,S,[#6;H2]([#8]-[#16])[#8],['O=S1(=O)CS(=O)(=O)OCO1'],fg1_fg2,O=S1(=O)CS(=O)(=O)OCO1,463,True,<rdkit.Chem.rdchem.Mol object at 0x7c09775b1360>
2,[#7;X3H0]([#6])([#6])([#6]),[#7],[#7&X3&H0]([#6]#[#7])([#6])[#6],[#7&X3&H0]([#6:1]#[#7:2])([#6])[#6],TRIPLE,C,N,[#6](#[#7])[#7;X3;H0]([#6])[#6],['N#CN1CCOCC1'],fg1_fg2,N#CN1CCOCC1,463,True,<rdkit.Chem.rdchem.Mol object at 0x7c08d231dbd0>
3,"[#7;X3H1+0,X3H2+0,X3H0+0][#7;X3H1+0,X3H2+0,X3H...",[#6],"[#7;X3&H1&+0,X3&H2&+0,X3&H0&+0]([#7;X3&H1&+0,X...","[#7;X3&H1&+0,X3&H2&+0,X3&H0&+0:1]([#7;X3&H1&+0...",SINGLE,N,C,"[#6]-[#7;X3&H0&+0,X3&H1&+0,X3&H2&+0][#7;X3&H0&...","['N#CCCNN', 'Cn1[nH]ccc1=O', 'CN1CCN(N)CC1']",fg1_fg2,N#CCCNN,463,True,<rdkit.Chem.rdchem.Mol object at 0x7c09775b13b0>
4,[#7;X3H0]([#6])([#6])([#6]),[#6],[#7&X3&H0]([#6]=[#6])([#6])[#6],[#7&X3&H0]([#6:1]=[#6:2])([#6])[#6],DOUBLE,C,C,[#6](=[#6])[#7;X3;H0]([#6])[#6],"['CC(=O)/C=C/N(C)C', 'C=C1N(C)c2ccccc2C1(C)C',...",fg1_fg2,CC(=O)/C=C/N(C)C,463,True,<rdkit.Chem.rdchem.Mol object at 0x7c09775b1400>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5742,[#16]1[#6][#16][#6]=[#6]1,[#6],[#16]1[#6]([#16][#6]=[#6]1)=[#6],[#16]1[#6:1]([#16][#6]=[#6]1)=[#6:2],DOUBLE,C,C,[#6]1(=[#6])([#16][#6]=[#6][#16]1),['C1=CSC(=C2SC=CS2)S1'],fg1_fg2,C1=CSC(=C2SC=CS2)S1,581,True,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fb1dd60>
5743,[#16]1[#6][#16][#6]=[#6]1,[#6][#16v2][#6],[#16]1[#6]([#16][#6]=[#6]1)=[#6][#16&v2][#6],[#16]1[#6:1]([#16][#6]=[#6]1)=[#6:2][#16&v2][#6],DOUBLE,C,C,[#6](=[#6]1([#16][#6]=[#6][#16]1))[#16;v2][#6],['C1=CSC(=C2SC=CS2)S1'],fg1_fg2,C1=CSC(=C2SC=CS2)S1,581,True,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fb1ddb0>
5744,[#16]1[#6][#16][#6]=[#6]1,[#16]1[#6][#16][#6]=[#6]1,[#16]1[#6]([#16][#6]=[#6]1)=[#6]1[#16][#6]=[#6...,[#16]1[#6:1]([#16][#6]=[#6]1)=[#6:2]1[#16][#6]...,DOUBLE,C,C,[#6]2(=[#6][#16][#6](=[#6]1([#16][#6]=[#6][#16...,['C1=CSC(=C2SC=CS2)S1'],fg1_fg2,C1=CSC(=C2SC=CS2)S1,581,True,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fb1de00>
5745,[#6]1[#8][#6][#7][#6]1,[CX4;!R][CX4;!R][CX4;!R],[#6]1[#8][#6][#7][#6]1-[C&X4&!R]([C&X4&!R])[C&...,[#6]1[#8][#6][#7][#6:1]1-[C&X4&!R:2]([C&X4&!R]...,SINGLE,C,C,[#6]1([#6]([#7][#6][#8]1)-[C;X4;!R]([C;X4;!R])...,['CC(C)[C@@H]1COC(=S)N1'],fg1_fg2,CC(C)[C@@H]1COC(=S)N1,581,True,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fb1de50>
5746,[#6]1[#8][#6][#7][#6]1,[#8],[#6]1([#8][#6][#7][#6]1)=[#8],[#6:1]1([#8][#6][#7][#6]1)=[#8:2],DOUBLE,C,O,[#6]1([#6][#7][#6][#8]1)=[#8],['CN1CC(=O)OC1=O'],fg1_fg2,CN1CC(=O)OC1=O,581,True,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fb1dea0>

In [17]:

df_1044['mol'] = df_1044['smiles'].apply(Chem.MolFromSmiles)
df_1044

,smiles,ac,amw,mol,is_463
0,O=C1NCCc2ccccc21,11,147.177002,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fa00740>,1
1,c1cnccn1,6,80.089996,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fa00cf0>,1
2,Cc1c[nH]cn1,6,82.106003,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fa00d60>,1
3,O=C1CCC1,5,70.091003,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fa009e0>,1
4,O=C1CSC(=O)N1,7,117.128998,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fa00dd0>,1
...,...,...,...,...,...
1039,O=C(O)c1cnsc1,8,129.139999,<rdkit.Chem.rdchem.Mol object at 0x7c0a2f9e6970>,1
1040,O=C1CSCC(=O)O1,8,132.139999,<rdkit.Chem.rdchem.Mol object at 0x7c0a2f9e69e0>,1
1041,c1ccc(-c2nnc(-c3ccccn3)nn2)nc1,18,236.238007,<rdkit.Chem.rdchem.Mol object at 0x7c0a2f9e6a50>,1
1042,O=C1COCCN1,7,101.105003,<rdkit.Chem.rdchem.Mol object at 0x7c0a2f9e6ac0>,1
1043,CCB(O)O,5,73.888000,<rdkit.Chem.rdchem.Mol object at 0x7c0a2f9e6b30>,1

In [18]:
def match_s(mol):
    res = []
    for row in df1.itertuples():
        if mol.HasSubstructMatch(row[-1]):
           res.append(row[8]) #fg1_fg2_marked 
    return res

In [19]:
df_1044['s'] = df_1044['mol'].parallel_apply(match_s)

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=131), Label(value='0 / 131'))), HB…

In [20]:
df_1044

,smiles,ac,amw,mol,is_463,s
0,O=C1NCCc2ccccc21,11,147.177002,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fa00740>,1,"[[#6](-[#6])[#7;X3;H1][#6], [#6]([#7;X3;H1][#6..."
1,c1cnccn1,6,80.089996,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fa00cf0>,1,"[[n]1([c](#[#8])[c]([n][c][c]1)#[#8]), [n]1(#[..."
2,Cc1c[nH]cn1,6,82.106003,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fa00d60>,1,"[[#6]-[#6], [#6]-[#6]1([#6][#7][#6][#7]1), [#6..."
3,O=C1CCC1,5,70.091003,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fa009e0>,1,"[[#6]=[#8], [#6]-[#6], [#6](-[#6])[#6]([#6])=[..."
4,O=C1CSC(=O)N1,7,117.128998,<rdkit.Chem.rdchem.Mol object at 0x7c0a2fa00dd0>,1,"[[#6](-[#6])[#7;X3;H1][#6], [#6](-[#16])[#7;X3..."
...,...,...,...,...,...,...
1039,O=C(O)c1cnsc1,8,129.139999,<rdkit.Chem.rdchem.Mol object at 0x7c0a2f9e6970>,1,"[[#6]-[#8], [#6]=[#8], [#6]-[#6], [#6](=[#8])-..."
1040,O=C1CSCC(=O)O1,8,132.139999,<rdkit.Chem.rdchem.Mol object at 0x7c0a2f9e69e0>,1,"[[#6]-[#16], [#6]-[#8], [#6]=[#8], [#6]-[#6], ..."
1041,c1ccc(-c2nnc(-c3ccccn3)nn2)nc1,18,236.238007,<rdkit.Chem.rdchem.Mol object at 0x7c0a2f9e6a50>,1,"[[#6]-[#6], [#6]1([#6][#6][#6][#6]([#7]1)-[c]2..."
1042,O=C1COCCN1,7,101.105003,<rdkit.Chem.rdchem.Mol object at 0x7c0a2f9e6ac0>,1,"[[#6](-[#6])[#7;X3;H1][#6], [#6]([#7;X3;H1][#6..."
1043,CCB(O)O,5,73.888000,<rdkit.Chem.rdchem.Mol object at 0x7c0a2f9e6b30>,1,"[[#6]-[#5], [#5]-[#8], [#6]-[#6], [#6;H3][#6;H..."

In [21]:
res = df_1044[['smiles','s']].explode('s')

In [22]:
res['s'].unique().__len__() #[res['s'].str.contains(':2')]#.sum() #补充相同的键

5747

In [139]:
res.to_csv('SMILES_bond.csv',index=False)

In [23]:
res.merge(inner_marked_comb[['smarts_inner_marked','smarts_marked_oxygen']],
          how='left',
          left_on='s',
          right_on='smarts_inner_marked')#.to_csv('SMILES_bond.csv',index=False)

KeyError: "None of [Index(['smarts_inner_marked', 'smarts_marked_oxygen'], dtype='object')] are in the [columns]"

In [25]:
tmp = res.merge(inner_marked_comb[['fg1_fg2_marked','canon_smarts']],
          how='left',
          left_on='s',
          right_on='canon_smarts')#.to_csv('SMILES_bond.csv',index=False)

In [ ]:
tmp.to_csv('SMILES_bond.csv',index=False)
tmp

,smiles,s,fg1_fg2_marked,canon_smarts
0,O=C1NCCc2ccccc21,[#6](-[#6])[#7;X3;H1][#6],[#7&X3&H1]([#6:1]-[#6:2])[#6],[#6](-[#6])[#7;X3;H1][#6]
1,O=C1NCCc2ccccc21,[#6]([#7;X3;H1][#6])=[#8],[#7&X3&H1]([#6:1]=[#8:2])[#6],[#6]([#7;X3;H1][#6])=[#8]
2,O=C1NCCc2ccccc21,[#6]=[#8],[#6:1]=[#8:2],[#6]=[#8]
3,O=C1NCCc2ccccc21,[#6]-[#7],[#6:1]-[#7:2],[#6]-[#7]
4,O=C1NCCc2ccccc21,[#6]-[#6],[#6:1]-[#6:2],[#6]-[#6]
...,...,...,...,...
138029,CCB(O)O,[#6][#5;X3](#[#8])([#8;H1]#[#8])[#8;H1],[#5&X3:1]([#8&H1])([#8&H1:2])[#6],[#6][#5;X3](#[#8])([#8;H1]#[#8])[#8;H1]
138030,CCB(O)O,[#6][#5;X3](#[#8])([#8;H1]#[#8])[#8;H1],[#5&X3:1]([#8&H1:2])([#8&H1])[#6],[#6][#5;X3](#[#8])([#8;H1]#[#8])[#8;H1]
138031,CCB(O)O,[#6][#5;X3](#[#8])([#8;H1]#[#8])[#8;H1],[#5&X3:1]([#8&H1])([#8&H1:2])[#6],[#6][#5;X3](#[#8])([#8;H1]#[#8])[#8;H1]
138032,CCB(O)O,[#6][#5;X3](#[#8])([#8;H1]#[#8])[#8;H1],[#5&X3:1]([#8&H1:2])([#8&H1])[#6],[#6][#5;X3](#[#8])([#8;H1]#[#8])[#8;H1]
138033,CCB(O)O,[#6;H3]([#6;H2]#[#8])#[#8],[#6&H2:1][#6&H3:2],[#6;H3]([#6;H2]#[#8])#[#8]